---
title: "Probabilistic pseudotime inference using Bayesian Gaussian Process Latent Variable Models"
author: "Kieran Campbell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

## Bayesian pseudogp fitting
```{r setup}
devtools::load_all("~/oxford/pseudogp")
library(ggplot2)
```

```{r firstfit, message = FALSE, warning = FALSE, fig.width=7, fig.height=4}
## first let's load the data
data(monocle_le)
data(monocle_pca)
data(monocle_tsne)

X <- data.frame(rbind(monocle_le, monocle_pca, monocle_tsne))
names(X) <- c("x1", "x2")
X$cell <- rep(1:nrow(monocle_le), times = 3)
X$representation <- rep(c("LE", "PCA", "tSNE"), each = nrow(monocle_le))
ggplot(X) + geom_point(aes(x = x1, y = x2)) + facet_wrap( ~ representation) + theme_bw()
```

Now we can prepare data and call the stan fit

```{r stanfit, cache=TRUE}
data <- list(LE = monocle_le, PCA = monocle_pca, tSNE = monocle_tsne)
fit <- fitPseudotime(data, chains = 2, iter = 1000, smoothing_alpha = 12, smoothing_beta = 3)
```

We can then use some of the inbuilt plotting functions

```{r boxplot, fig.width = 8, fig.height = 6}
posteriorBoxplot(fit)
```

And look at the posterior curves, both means and samples:

```{r boxplot, fig.width = 8, fig.height = 6}
posteriorCurvePlot(data, fit) # plot the mean curve
posteriorCurvePlot(data, fit, posterior_mean = FALSE) # plot posterior samples
```


